//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:19:45 em CET 
//


package se.sparavisering;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Underlag för utfilen för avisering
 * 
 * <p>Java class for AviseringsunderlagTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AviseringsunderlagTYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}ResultatfilSkapad" minOccurs="0"/>
 *         &lt;element name="Kundinfil" type="{http://skatteverket.se/spar/komponent/1.0}KundinfilInformationTYPE" minOccurs="0"/>
 *         &lt;element name="Folkbokforingsfil" type="{http://skatteverket.se/spar/komponent/1.0}FolkbokforingsfilInformationTYPE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AviseringsunderlagTYPE", propOrder = {
    "resultatfilSkapad",
    "kundinfil",
    "folkbokforingsfil"
})
public class AviseringsunderlagTYPE {

    @XmlElement(name = "ResultatfilSkapad")
    protected XMLGregorianCalendar resultatfilSkapad;
    @XmlElementRef(name = "Kundinfil", namespace = "http://skatteverket.se/spar/komponent/1.0", type = JAXBElement.class)
    protected JAXBElement<KundinfilInformationTYPE> kundinfil;
    @XmlElementRef(name = "Folkbokforingsfil", namespace = "http://skatteverket.se/spar/komponent/1.0", type = JAXBElement.class)
    protected JAXBElement<FolkbokforingsfilInformationTYPE> folkbokforingsfil;

    /**
     * Gets the value of the resultatfilSkapad property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getResultatfilSkapad() {
        return resultatfilSkapad;
    }

    /**
     * Sets the value of the resultatfilSkapad property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setResultatfilSkapad(XMLGregorianCalendar value) {
        this.resultatfilSkapad = value;
    }

    /**
     * Gets the value of the kundinfil property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link KundinfilInformationTYPE }{@code >}
     *     
     */
    public JAXBElement<KundinfilInformationTYPE> getKundinfil() {
        return kundinfil;
    }

    /**
     * Sets the value of the kundinfil property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link KundinfilInformationTYPE }{@code >}
     *     
     */
    public void setKundinfil(JAXBElement<KundinfilInformationTYPE> value) {
        this.kundinfil = ((JAXBElement<KundinfilInformationTYPE> ) value);
    }

    /**
     * Gets the value of the folkbokforingsfil property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FolkbokforingsfilInformationTYPE }{@code >}
     *     
     */
    public JAXBElement<FolkbokforingsfilInformationTYPE> getFolkbokforingsfil() {
        return folkbokforingsfil;
    }

    /**
     * Sets the value of the folkbokforingsfil property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FolkbokforingsfilInformationTYPE }{@code >}
     *     
     */
    public void setFolkbokforingsfil(JAXBElement<FolkbokforingsfilInformationTYPE> value) {
        this.folkbokforingsfil = ((JAXBElement<FolkbokforingsfilInformationTYPE> ) value);
    }

}
