//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:19:45 em CET 
//


package se.sparavisering;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * En komplett post med personinformation för en fysisk person i SPAR
 * 
 * <p>Java class for AviseringsPostTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AviseringsPostTYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}PersonId"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}Sekretessmarkering"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}SekretessAndringsdatum" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}SenasteAndringFolkbokforing" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}TaxeradInkomst" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}Taxeringsar" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}Persondetaljer" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}Adress" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}Relation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}Fastighet" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AviseringsPostTYPE", propOrder = {
    "personId",
    "sekretessmarkering",
    "sekretessAndringsdatum",
    "senasteAndringFolkbokforing",
    "taxeradInkomst",
    "taxeringsar",
    "persondetaljer",
    "adress",
    "relation",
    "fastighet"
})
public class AviseringsPostTYPE {

    @XmlElement(name = "PersonId", required = true)
    protected PersonIdTYPE personId;
    @XmlElement(name = "Sekretessmarkering", required = true)
    protected SekretessmarkeringTYPE sekretessmarkering;
    @XmlElement(name = "SekretessAndringsdatum")
    protected XMLGregorianCalendar sekretessAndringsdatum;
    @XmlElement(name = "SenasteAndringFolkbokforing")
    protected XMLGregorianCalendar senasteAndringFolkbokforing;
    @XmlElement(name = "TaxeradInkomst")
    protected String taxeradInkomst;
    @XmlElement(name = "Taxeringsar")
    protected String taxeringsar;
    @XmlElement(name = "Persondetaljer")
    protected List<PersondetaljerTYPE> persondetaljer;
    @XmlElement(name = "Adress")
    protected List<AdressTYPE> adress;
    @XmlElement(name = "Relation")
    protected List<RelationTYPE> relation;
    @XmlElement(name = "Fastighet")
    protected List<FastighetTYPE> fastighet;

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link PersonIdTYPE }
     *     
     */
    public PersonIdTYPE getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonIdTYPE }
     *     
     */
    public void setPersonId(PersonIdTYPE value) {
        this.personId = value;
    }

    /**
     * Gets the value of the sekretessmarkering property.
     * 
     * @return
     *     possible object is
     *     {@link SekretessmarkeringTYPE }
     *     
     */
    public SekretessmarkeringTYPE getSekretessmarkering() {
        return sekretessmarkering;
    }

    /**
     * Sets the value of the sekretessmarkering property.
     * 
     * @param value
     *     allowed object is
     *     {@link SekretessmarkeringTYPE }
     *     
     */
    public void setSekretessmarkering(SekretessmarkeringTYPE value) {
        this.sekretessmarkering = value;
    }

    /**
     * Gets the value of the sekretessAndringsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSekretessAndringsdatum() {
        return sekretessAndringsdatum;
    }

    /**
     * Sets the value of the sekretessAndringsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSekretessAndringsdatum(XMLGregorianCalendar value) {
        this.sekretessAndringsdatum = value;
    }

    /**
     * Gets the value of the senasteAndringFolkbokforing property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSenasteAndringFolkbokforing() {
        return senasteAndringFolkbokforing;
    }

    /**
     * Sets the value of the senasteAndringFolkbokforing property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSenasteAndringFolkbokforing(XMLGregorianCalendar value) {
        this.senasteAndringFolkbokforing = value;
    }

    /**
     * Gets the value of the taxeradInkomst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxeradInkomst() {
        return taxeradInkomst;
    }

    /**
     * Sets the value of the taxeradInkomst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxeradInkomst(String value) {
        this.taxeradInkomst = value;
    }

    /**
     * Gets the value of the taxeringsar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxeringsar() {
        return taxeringsar;
    }

    /**
     * Sets the value of the taxeringsar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxeringsar(String value) {
        this.taxeringsar = value;
    }

    /**
     * Gets the value of the persondetaljer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the persondetaljer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersondetaljer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersondetaljerTYPE }
     * 
     * 
     */
    public List<PersondetaljerTYPE> getPersondetaljer() {
        if (persondetaljer == null) {
            persondetaljer = new ArrayList<PersondetaljerTYPE>();
        }
        return this.persondetaljer;
    }

    /**
     * Gets the value of the adress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdressTYPE }
     * 
     * 
     */
    public List<AdressTYPE> getAdress() {
        if (adress == null) {
            adress = new ArrayList<AdressTYPE>();
        }
        return this.adress;
    }

    /**
     * Gets the value of the relation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationTYPE }
     * 
     * 
     */
    public List<RelationTYPE> getRelation() {
        if (relation == null) {
            relation = new ArrayList<RelationTYPE>();
        }
        return this.relation;
    }

    /**
     * Gets the value of the fastighet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fastighet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFastighet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FastighetTYPE }
     * 
     * 
     */
    public List<FastighetTYPE> getFastighet() {
        if (fastighet == null) {
            fastighet = new ArrayList<FastighetTYPE>();
        }
        return this.fastighet;
    }

}
