//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:19:45 em CET 
//


package se.sparavisering;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AvregistreringsorsakKodTYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AvregistreringsorsakKodTYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="O"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AvregistreringsorsakKodTYPE")
@XmlEnum
public enum AvregistreringsorsakKodTYPE {


    /**
     * Avliden
     * 
     */
    A,

    /**
     * Gammalt nummer
     * 
     */
    G,

    /**
     * Övrig orsak
     * 
     */
    O;

    public String value() {
        return name();
    }

    public static AvregistreringsorsakKodTYPE fromValue(String v) {
        return valueOf(v);
    }

}
