//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:19:45 em CET 
//


package se.sparavisering;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Sammanhållande element för en fastighet som personen äger hela eller delar av.
 * 
 * <p>Java class for FastighetTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FastighetTYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}FastighetLanKod"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}FastighetKommunKod"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}IdTaxenhet" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}FastighetsKod"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}AndelstalTaljare"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}AndelstalNamnare"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}Taxeringsar" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}Taxeringsvarde"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}AndringsDatum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FastighetTYPE", propOrder = {
    "fastighetLanKod",
    "fastighetKommunKod",
    "idTaxenhet",
    "fastighetsKod",
    "andelstalTaljare",
    "andelstalNamnare",
    "taxeringsar",
    "taxeringsvarde",
    "andringsDatum"
})
public class FastighetTYPE {

    @XmlElement(name = "FastighetLanKod", required = true)
    protected String fastighetLanKod;
    @XmlElement(name = "FastighetKommunKod", required = true)
    protected String fastighetKommunKod;
    @XmlElement(name = "IdTaxenhet")
    protected String idTaxenhet;
    @XmlElement(name = "FastighetsKod", required = true)
    protected FastighetsKodTYPE fastighetsKod;
    @XmlElement(name = "AndelstalTaljare", required = true)
    protected BigInteger andelstalTaljare;
    @XmlElement(name = "AndelstalNamnare", required = true)
    protected BigInteger andelstalNamnare;
    @XmlElement(name = "Taxeringsar")
    protected String taxeringsar;
    @XmlElement(name = "Taxeringsvarde", required = true)
    protected String taxeringsvarde;
    @XmlElement(name = "AndringsDatum")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar andringsDatum;

    /**
     * Gets the value of the fastighetLanKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFastighetLanKod() {
        return fastighetLanKod;
    }

    /**
     * Sets the value of the fastighetLanKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFastighetLanKod(String value) {
        this.fastighetLanKod = value;
    }

    /**
     * Gets the value of the fastighetKommunKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFastighetKommunKod() {
        return fastighetKommunKod;
    }

    /**
     * Sets the value of the fastighetKommunKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFastighetKommunKod(String value) {
        this.fastighetKommunKod = value;
    }

    /**
     * Gets the value of the idTaxenhet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTaxenhet() {
        return idTaxenhet;
    }

    /**
     * Sets the value of the idTaxenhet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTaxenhet(String value) {
        this.idTaxenhet = value;
    }

    /**
     * Gets the value of the fastighetsKod property.
     * 
     * @return
     *     possible object is
     *     {@link FastighetsKodTYPE }
     *     
     */
    public FastighetsKodTYPE getFastighetsKod() {
        return fastighetsKod;
    }

    /**
     * Sets the value of the fastighetsKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link FastighetsKodTYPE }
     *     
     */
    public void setFastighetsKod(FastighetsKodTYPE value) {
        this.fastighetsKod = value;
    }

    /**
     * Gets the value of the andelstalTaljare property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAndelstalTaljare() {
        return andelstalTaljare;
    }

    /**
     * Sets the value of the andelstalTaljare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAndelstalTaljare(BigInteger value) {
        this.andelstalTaljare = value;
    }

    /**
     * Gets the value of the andelstalNamnare property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAndelstalNamnare() {
        return andelstalNamnare;
    }

    /**
     * Sets the value of the andelstalNamnare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAndelstalNamnare(BigInteger value) {
        this.andelstalNamnare = value;
    }

    /**
     * Gets the value of the taxeringsar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxeringsar() {
        return taxeringsar;
    }

    /**
     * Sets the value of the taxeringsar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxeringsar(String value) {
        this.taxeringsar = value;
    }

    /**
     * Gets the value of the taxeringsvarde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxeringsvarde() {
        return taxeringsvarde;
    }

    /**
     * Sets the value of the taxeringsvarde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxeringsvarde(String value) {
        this.taxeringsvarde = value;
    }

    /**
     * Gets the value of the andringsDatum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAndringsDatum() {
        return andringsDatum;
    }

    /**
     * Sets the value of the andringsDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAndringsDatum(XMLGregorianCalendar value) {
        this.andringsDatum = value;
    }

}
