//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:19:45 em CET 
//


package se.sparavisering;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdentifieringsInformationFilTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentifieringsInformationFilTYPE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Medieleverantor" type="{http://skatteverket.se/spar/komponent/1.0}MedieinformationTYPE"/>
 *         &lt;element name="Mediemottagare" type="{http://skatteverket.se/spar/komponent/1.0}MedieinformationTYPE"/>
 *         &lt;element name="Filinformation" type="{http://skatteverket.se/spar/komponent/1.0}FilinformationTYPE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentifieringsInformationFilTYPE", propOrder = {
    "medieleverantor",
    "mediemottagare",
    "filinformation"
})
public class IdentifieringsInformationFilTYPE {

    @XmlElement(name = "Medieleverantor", required = true, nillable = true)
    protected MedieinformationTYPE medieleverantor;
    @XmlElement(name = "Mediemottagare", required = true, nillable = true)
    protected MedieinformationTYPE mediemottagare;
    @XmlElement(name = "Filinformation", required = true, nillable = true)
    protected FilinformationTYPE filinformation;

    /**
     * Gets the value of the medieleverantor property.
     * 
     * @return
     *     possible object is
     *     {@link MedieinformationTYPE }
     *     
     */
    public MedieinformationTYPE getMedieleverantor() {
        return medieleverantor;
    }

    /**
     * Sets the value of the medieleverantor property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedieinformationTYPE }
     *     
     */
    public void setMedieleverantor(MedieinformationTYPE value) {
        this.medieleverantor = value;
    }

    /**
     * Gets the value of the mediemottagare property.
     * 
     * @return
     *     possible object is
     *     {@link MedieinformationTYPE }
     *     
     */
    public MedieinformationTYPE getMediemottagare() {
        return mediemottagare;
    }

    /**
     * Sets the value of the mediemottagare property.
     * 
     * @param value
     *     allowed object is
     *     {@link MedieinformationTYPE }
     *     
     */
    public void setMediemottagare(MedieinformationTYPE value) {
        this.mediemottagare = value;
    }

    /**
     * Gets the value of the filinformation property.
     * 
     * @return
     *     possible object is
     *     {@link FilinformationTYPE }
     *     
     */
    public FilinformationTYPE getFilinformation() {
        return filinformation;
    }

    /**
     * Sets the value of the filinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilinformationTYPE }
     *     
     */
    public void setFilinformation(FilinformationTYPE value) {
        this.filinformation = value;
    }

}
