//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:19:45 em CET 
//


package se.sparavisering;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.sparavisering package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _KommunKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "KommunKod");
    private final static QName _ForsamlingKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "ForsamlingKod");
    private final static QName _FodelsetidTill_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FodelsetidTill");
    private final static QName _Fodelseforsamling_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Fodelseforsamling");
    private final static QName _UppdragsId_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "UppdragsId");
    private final static QName _Relation_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Relation");
    private final static QName _Postort_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Postort");
    private final static QName _ForMellanEfterNamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "ForMellanEfterNamn");
    private final static QName _Sekretessmarkering_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Sekretessmarkering");
    private final static QName _Taxeringsvarde_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Taxeringsvarde");
    private final static QName _AndelstalTaljare_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "AndelstalTaljare");
    private final static QName _FolkbokfordLanKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FolkbokfordLanKod");
    private final static QName _Aviseringsnamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Aviseringsnamn");
    private final static QName _SvenskMedborgare_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SvenskMedborgare");
    private final static QName _Folkbokforingsdatum_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Folkbokforingsdatum");
    private final static QName _FolkbokfordForsamlingKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FolkbokfordForsamlingKod");
    private final static QName _SarskildPostadress_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SarskildPostadress");
    private final static QName _PostortUtland_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "PostortUtland");
    private final static QName _Relationstyp_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Relationstyp");
    private final static QName _AviseringsPoster_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "AviseringsPoster");
    private final static QName _Utdelningsadress2_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Utdelningsadress2");
    private final static QName _LanKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "LanKod");
    private final static QName _TaxeradInkomst_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "TaxeradInkomst");
    private final static QName _Utdelningsadress1_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Utdelningsadress1");
    private final static QName _Utdelningsadress3_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Utdelningsadress3");
    private final static QName _PostNr_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "PostNr");
    private final static QName _PostKodUtland_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "PostKodUtland");
    private final static QName _AviseringsPost_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "AviseringsPost");
    private final static QName _Aviseringsunderlag_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Aviseringsunderlag");
    private final static QName _IdentifieringsInformation_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "IdentifieringsInformation");
    private final static QName _FolkbokforingsKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FolkbokforingsKod");
    private final static QName _Kon_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Kon");
    private final static QName _Utlandsadress_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Utlandsadress");
    private final static QName _AvregistreringsorsakKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "AvregistreringsorsakKod");
    private final static QName _IdentifieringsInformationFil_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "IdentifieringsInformationFil");
    private final static QName _Fodelsetid_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Fodelsetid");
    private final static QName _Fastighet_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Fastighet");
    private final static QName _Fornamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Fornamn");
    private final static QName _SekretessAndringsdatum_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SekretessAndringsdatum");
    private final static QName _OrgNrSlutkund_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "OrgNrSlutkund");
    private final static QName _HanvisningsPersonNrByttFran_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "HanvisningsPersonNrByttFran");
    private final static QName _HanvisningsPersonNrByttTill_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "HanvisningsPersonNrByttTill");
    private final static QName _FysiskPersonId_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FysiskPersonId");
    private final static QName _AndelstalNamnare_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "AndelstalNamnare");
    private final static QName _Persondetaljer_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Persondetaljer");
    private final static QName _Tillskrift_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Tillskrift");
    private final static QName _FodelsetidFran_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FodelsetidFran");
    private final static QName _Tilltalsnamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Tilltalsnamn");
    private final static QName _KundNrLeveransMottagare_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "KundNrLeveransMottagare");
    private final static QName _CareOf_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "CareOf");
    private final static QName _SlutAnvandarId_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SlutAnvandarId");
    private final static QName _IdTaxenhet_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "IdTaxenhet");
    private final static QName _FastighetKommunKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FastighetKommunKod");
    private final static QName _Folkbokforingsadress_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Folkbokforingsadress");
    private final static QName _FastighetsKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FastighetsKod");
    private final static QName _Taxeringsar_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Taxeringsar");
    private final static QName _DatumFrom_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "DatumFrom");
    private final static QName _Efternamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Efternamn");
    private final static QName _Mellannamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Mellannamn");
    private final static QName _Landskod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Landskod");
    private final static QName _KundNr_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "KundNr");
    private final static QName _SlutAnvandarBehorighet_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SlutAnvandarBehorighet");
    private final static QName _Avregistreringsdatum_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Avregistreringsdatum");
    private final static QName _Tidsstampel_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Tidsstampel");
    private final static QName _SenasteAndringFolkbokforing_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SenasteAndringFolkbokforing");
    private final static QName _PersonId_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "PersonId");
    private final static QName _Adress_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Adress");
    private final static QName _FastighetLanKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FastighetLanKod");
    private final static QName _ResultatfilSkapad_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "ResultatfilSkapad");
    private final static QName _Land_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Land");
    private final static QName _DatumTom_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "DatumTom");
    private final static QName _FodelselanKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FodelselanKod");
    private final static QName _KundNrSlutkund_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "KundNrSlutkund");
    private final static QName _SlutAnvandarSekretessRatt_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SlutAnvandarSekretessRatt");
    private final static QName _AndringsDatum_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "AndringsDatum");
    private final static QName _FolkbokfordKommunKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FolkbokfordKommunKod");
    private final static QName _HanvisningsPersonNr_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "HanvisningsPersonNr");
    private final static QName _TidsstampelAvisering_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "TidsstampelAvisering");
    private final static QName _OrgNr_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "OrgNr");
    private final static QName _AviseringsunderlagTYPEFolkbokforingsfil_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Folkbokforingsfil");
    private final static QName _AviseringsunderlagTYPEKundinfil_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Kundinfil");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.sparavisering
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RelationTYPE }
     * 
     */
    public RelationTYPE createRelationTYPE() {
        return new RelationTYPE();
    }

    /**
     * Create an instance of {@link KundinfilInformationTYPE }
     * 
     */
    public KundinfilInformationTYPE createKundinfilInformationTYPE() {
        return new KundinfilInformationTYPE();
    }

    /**
     * Create an instance of {@link FolkbokforingsfilInformationTYPE }
     * 
     */
    public FolkbokforingsfilInformationTYPE createFolkbokforingsfilInformationTYPE() {
        return new FolkbokforingsfilInformationTYPE();
    }

    /**
     * Create an instance of {@link UtlandsadressTYPE }
     * 
     */
    public UtlandsadressTYPE createUtlandsadressTYPE() {
        return new UtlandsadressTYPE();
    }

    /**
     * Create an instance of {@link SPARAvisering }
     * 
     */
    public SPARAvisering createSPARAvisering() {
        return new SPARAvisering();
    }

    /**
     * Create an instance of {@link FastighetTYPE }
     * 
     */
    public FastighetTYPE createFastighetTYPE() {
        return new FastighetTYPE();
    }

    /**
     * Create an instance of {@link ForMellanEfterNamnTYPE }
     * 
     */
    public ForMellanEfterNamnTYPE createForMellanEfterNamnTYPE() {
        return new ForMellanEfterNamnTYPE();
    }

    /**
     * Create an instance of {@link FolkbokforingsadressTYPE }
     * 
     */
    public FolkbokforingsadressTYPE createFolkbokforingsadressTYPE() {
        return new FolkbokforingsadressTYPE();
    }

    /**
     * Create an instance of {@link AviseringsunderlagTYPE }
     * 
     */
    public AviseringsunderlagTYPE createAviseringsunderlagTYPE() {
        return new AviseringsunderlagTYPE();
    }

    /**
     * Create an instance of {@link PersondetaljerTYPE }
     * 
     */
    public PersondetaljerTYPE createPersondetaljerTYPE() {
        return new PersondetaljerTYPE();
    }

    /**
     * Create an instance of {@link AdressTYPE }
     * 
     */
    public AdressTYPE createAdressTYPE() {
        return new AdressTYPE();
    }

    /**
     * Create an instance of {@link IdentifieringsInformationFilTYPE }
     * 
     */
    public IdentifieringsInformationFilTYPE createIdentifieringsInformationFilTYPE() {
        return new IdentifieringsInformationFilTYPE();
    }

    /**
     * Create an instance of {@link PersonIdTYPE }
     * 
     */
    public PersonIdTYPE createPersonIdTYPE() {
        return new PersonIdTYPE();
    }

    /**
     * Create an instance of {@link MedieinformationTYPE }
     * 
     */
    public MedieinformationTYPE createMedieinformationTYPE() {
        return new MedieinformationTYPE();
    }

    /**
     * Create an instance of {@link IdentifieringsInformationTYPE }
     * 
     */
    public IdentifieringsInformationTYPE createIdentifieringsInformationTYPE() {
        return new IdentifieringsInformationTYPE();
    }

    /**
     * Create an instance of {@link FilinformationTYPE }
     * 
     */
    public FilinformationTYPE createFilinformationTYPE() {
        return new FilinformationTYPE();
    }

    /**
     * Create an instance of {@link AviseringsPosterTYPE }
     * 
     */
    public AviseringsPosterTYPE createAviseringsPosterTYPE() {
        return new AviseringsPosterTYPE();
    }

    /**
     * Create an instance of {@link SarskildPostadressTYPE }
     * 
     */
    public SarskildPostadressTYPE createSarskildPostadressTYPE() {
        return new SarskildPostadressTYPE();
    }

    /**
     * Create an instance of {@link AviseringsPostTYPE }
     * 
     */
    public AviseringsPostTYPE createAviseringsPostTYPE() {
        return new AviseringsPostTYPE();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "KommunKod")
    public JAXBElement<String> createKommunKod(String value) {
        return new JAXBElement<String>(_KommunKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "ForsamlingKod")
    public JAXBElement<String> createForsamlingKod(String value) {
        return new JAXBElement<String>(_ForsamlingKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FodelsetidTill")
    public JAXBElement<XMLGregorianCalendar> createFodelsetidTill(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_FodelsetidTill_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Fodelseforsamling")
    public JAXBElement<String> createFodelseforsamling(String value) {
        return new JAXBElement<String>(_Fodelseforsamling_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "UppdragsId")
    public JAXBElement<Long> createUppdragsId(Long value) {
        return new JAXBElement<Long>(_UppdragsId_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Relation")
    public JAXBElement<RelationTYPE> createRelation(RelationTYPE value) {
        return new JAXBElement<RelationTYPE>(_Relation_QNAME, RelationTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Postort")
    public JAXBElement<String> createPostort(String value) {
        return new JAXBElement<String>(_Postort_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForMellanEfterNamnTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "ForMellanEfterNamn")
    public JAXBElement<ForMellanEfterNamnTYPE> createForMellanEfterNamn(ForMellanEfterNamnTYPE value) {
        return new JAXBElement<ForMellanEfterNamnTYPE>(_ForMellanEfterNamn_QNAME, ForMellanEfterNamnTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SekretessmarkeringTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Sekretessmarkering")
    public JAXBElement<SekretessmarkeringTYPE> createSekretessmarkering(SekretessmarkeringTYPE value) {
        return new JAXBElement<SekretessmarkeringTYPE>(_Sekretessmarkering_QNAME, SekretessmarkeringTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Taxeringsvarde")
    public JAXBElement<String> createTaxeringsvarde(String value) {
        return new JAXBElement<String>(_Taxeringsvarde_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "AndelstalTaljare")
    public JAXBElement<BigInteger> createAndelstalTaljare(BigInteger value) {
        return new JAXBElement<BigInteger>(_AndelstalTaljare_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FolkbokfordLanKod")
    public JAXBElement<String> createFolkbokfordLanKod(String value) {
        return new JAXBElement<String>(_FolkbokfordLanKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Aviseringsnamn")
    public JAXBElement<String> createAviseringsnamn(String value) {
        return new JAXBElement<String>(_Aviseringsnamn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SvenskMedborgareTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SvenskMedborgare")
    public JAXBElement<SvenskMedborgareTYPE> createSvenskMedborgare(SvenskMedborgareTYPE value) {
        return new JAXBElement<SvenskMedborgareTYPE>(_SvenskMedborgare_QNAME, SvenskMedborgareTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Folkbokforingsdatum")
    public JAXBElement<XMLGregorianCalendar> createFolkbokforingsdatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Folkbokforingsdatum_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FolkbokfordForsamlingKod")
    public JAXBElement<String> createFolkbokfordForsamlingKod(String value) {
        return new JAXBElement<String>(_FolkbokfordForsamlingKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SarskildPostadressTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SarskildPostadress")
    public JAXBElement<SarskildPostadressTYPE> createSarskildPostadress(SarskildPostadressTYPE value) {
        return new JAXBElement<SarskildPostadressTYPE>(_SarskildPostadress_QNAME, SarskildPostadressTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "PostortUtland")
    public JAXBElement<String> createPostortUtland(String value) {
        return new JAXBElement<String>(_PostortUtland_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationstypTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Relationstyp")
    public JAXBElement<RelationstypTYPE> createRelationstyp(RelationstypTYPE value) {
        return new JAXBElement<RelationstypTYPE>(_Relationstyp_QNAME, RelationstypTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AviseringsPosterTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "AviseringsPoster")
    public JAXBElement<AviseringsPosterTYPE> createAviseringsPoster(AviseringsPosterTYPE value) {
        return new JAXBElement<AviseringsPosterTYPE>(_AviseringsPoster_QNAME, AviseringsPosterTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Utdelningsadress2")
    public JAXBElement<String> createUtdelningsadress2(String value) {
        return new JAXBElement<String>(_Utdelningsadress2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "LanKod")
    public JAXBElement<String> createLanKod(String value) {
        return new JAXBElement<String>(_LanKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "TaxeradInkomst")
    public JAXBElement<String> createTaxeradInkomst(String value) {
        return new JAXBElement<String>(_TaxeradInkomst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Utdelningsadress1")
    public JAXBElement<String> createUtdelningsadress1(String value) {
        return new JAXBElement<String>(_Utdelningsadress1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Utdelningsadress3")
    public JAXBElement<String> createUtdelningsadress3(String value) {
        return new JAXBElement<String>(_Utdelningsadress3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "PostNr")
    public JAXBElement<String> createPostNr(String value) {
        return new JAXBElement<String>(_PostNr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "PostKodUtland")
    public JAXBElement<String> createPostKodUtland(String value) {
        return new JAXBElement<String>(_PostKodUtland_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AviseringsPostTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "AviseringsPost")
    public JAXBElement<AviseringsPostTYPE> createAviseringsPost(AviseringsPostTYPE value) {
        return new JAXBElement<AviseringsPostTYPE>(_AviseringsPost_QNAME, AviseringsPostTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AviseringsunderlagTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Aviseringsunderlag")
    public JAXBElement<AviseringsunderlagTYPE> createAviseringsunderlag(AviseringsunderlagTYPE value) {
        return new JAXBElement<AviseringsunderlagTYPE>(_Aviseringsunderlag_QNAME, AviseringsunderlagTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifieringsInformationTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "IdentifieringsInformation")
    public JAXBElement<IdentifieringsInformationTYPE> createIdentifieringsInformation(IdentifieringsInformationTYPE value) {
        return new JAXBElement<IdentifieringsInformationTYPE>(_IdentifieringsInformation_QNAME, IdentifieringsInformationTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FolkbokforingsKod")
    public JAXBElement<String> createFolkbokforingsKod(String value) {
        return new JAXBElement<String>(_FolkbokforingsKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KonTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Kon")
    public JAXBElement<KonTYPE> createKon(KonTYPE value) {
        return new JAXBElement<KonTYPE>(_Kon_QNAME, KonTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UtlandsadressTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Utlandsadress")
    public JAXBElement<UtlandsadressTYPE> createUtlandsadress(UtlandsadressTYPE value) {
        return new JAXBElement<UtlandsadressTYPE>(_Utlandsadress_QNAME, UtlandsadressTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvregistreringsorsakKodTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "AvregistreringsorsakKod")
    public JAXBElement<AvregistreringsorsakKodTYPE> createAvregistreringsorsakKod(AvregistreringsorsakKodTYPE value) {
        return new JAXBElement<AvregistreringsorsakKodTYPE>(_AvregistreringsorsakKod_QNAME, AvregistreringsorsakKodTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifieringsInformationFilTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "IdentifieringsInformationFil")
    public JAXBElement<IdentifieringsInformationFilTYPE> createIdentifieringsInformationFil(IdentifieringsInformationFilTYPE value) {
        return new JAXBElement<IdentifieringsInformationFilTYPE>(_IdentifieringsInformationFil_QNAME, IdentifieringsInformationFilTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Fodelsetid")
    public JAXBElement<XMLGregorianCalendar> createFodelsetid(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Fodelsetid_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FastighetTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Fastighet")
    public JAXBElement<FastighetTYPE> createFastighet(FastighetTYPE value) {
        return new JAXBElement<FastighetTYPE>(_Fastighet_QNAME, FastighetTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Fornamn")
    public JAXBElement<String> createFornamn(String value) {
        return new JAXBElement<String>(_Fornamn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SekretessAndringsdatum")
    public JAXBElement<XMLGregorianCalendar> createSekretessAndringsdatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SekretessAndringsdatum_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "OrgNrSlutkund")
    public JAXBElement<String> createOrgNrSlutkund(String value) {
        return new JAXBElement<String>(_OrgNrSlutkund_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "HanvisningsPersonNrByttFran")
    public JAXBElement<String> createHanvisningsPersonNrByttFran(String value) {
        return new JAXBElement<String>(_HanvisningsPersonNrByttFran_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "HanvisningsPersonNrByttTill")
    public JAXBElement<String> createHanvisningsPersonNrByttTill(String value) {
        return new JAXBElement<String>(_HanvisningsPersonNrByttTill_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FysiskPersonId")
    public JAXBElement<String> createFysiskPersonId(String value) {
        return new JAXBElement<String>(_FysiskPersonId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "AndelstalNamnare")
    public JAXBElement<BigInteger> createAndelstalNamnare(BigInteger value) {
        return new JAXBElement<BigInteger>(_AndelstalNamnare_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersondetaljerTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Persondetaljer")
    public JAXBElement<PersondetaljerTYPE> createPersondetaljer(PersondetaljerTYPE value) {
        return new JAXBElement<PersondetaljerTYPE>(_Persondetaljer_QNAME, PersondetaljerTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Tillskrift")
    public JAXBElement<String> createTillskrift(String value) {
        return new JAXBElement<String>(_Tillskrift_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FodelsetidFran")
    public JAXBElement<XMLGregorianCalendar> createFodelsetidFran(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_FodelsetidFran_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Tilltalsnamn")
    public JAXBElement<Integer> createTilltalsnamn(Integer value) {
        return new JAXBElement<Integer>(_Tilltalsnamn_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "KundNrLeveransMottagare")
    public JAXBElement<Integer> createKundNrLeveransMottagare(Integer value) {
        return new JAXBElement<Integer>(_KundNrLeveransMottagare_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "CareOf")
    public JAXBElement<String> createCareOf(String value) {
        return new JAXBElement<String>(_CareOf_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SlutAnvandarId")
    public JAXBElement<String> createSlutAnvandarId(String value) {
        return new JAXBElement<String>(_SlutAnvandarId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "IdTaxenhet")
    public JAXBElement<String> createIdTaxenhet(String value) {
        return new JAXBElement<String>(_IdTaxenhet_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FastighetKommunKod")
    public JAXBElement<String> createFastighetKommunKod(String value) {
        return new JAXBElement<String>(_FastighetKommunKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FolkbokforingsadressTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Folkbokforingsadress")
    public JAXBElement<FolkbokforingsadressTYPE> createFolkbokforingsadress(FolkbokforingsadressTYPE value) {
        return new JAXBElement<FolkbokforingsadressTYPE>(_Folkbokforingsadress_QNAME, FolkbokforingsadressTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FastighetsKodTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FastighetsKod")
    public JAXBElement<FastighetsKodTYPE> createFastighetsKod(FastighetsKodTYPE value) {
        return new JAXBElement<FastighetsKodTYPE>(_FastighetsKod_QNAME, FastighetsKodTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Taxeringsar")
    public JAXBElement<String> createTaxeringsar(String value) {
        return new JAXBElement<String>(_Taxeringsar_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "DatumFrom")
    public JAXBElement<XMLGregorianCalendar> createDatumFrom(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumFrom_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Efternamn")
    public JAXBElement<String> createEfternamn(String value) {
        return new JAXBElement<String>(_Efternamn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Mellannamn")
    public JAXBElement<String> createMellannamn(String value) {
        return new JAXBElement<String>(_Mellannamn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Landskod")
    public JAXBElement<String> createLandskod(String value) {
        return new JAXBElement<String>(_Landskod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "KundNr")
    public JAXBElement<Integer> createKundNr(Integer value) {
        return new JAXBElement<Integer>(_KundNr_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlutAnvandarBehorighetTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SlutAnvandarBehorighet")
    public JAXBElement<SlutAnvandarBehorighetTYPE> createSlutAnvandarBehorighet(SlutAnvandarBehorighetTYPE value) {
        return new JAXBElement<SlutAnvandarBehorighetTYPE>(_SlutAnvandarBehorighet_QNAME, SlutAnvandarBehorighetTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Avregistreringsdatum")
    public JAXBElement<String> createAvregistreringsdatum(String value) {
        return new JAXBElement<String>(_Avregistreringsdatum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Tidsstampel")
    public JAXBElement<XMLGregorianCalendar> createTidsstampel(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Tidsstampel_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SenasteAndringFolkbokforing")
    public JAXBElement<XMLGregorianCalendar> createSenasteAndringFolkbokforing(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SenasteAndringFolkbokforing_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonIdTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "PersonId")
    public JAXBElement<PersonIdTYPE> createPersonId(PersonIdTYPE value) {
        return new JAXBElement<PersonIdTYPE>(_PersonId_QNAME, PersonIdTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdressTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Adress")
    public JAXBElement<AdressTYPE> createAdress(AdressTYPE value) {
        return new JAXBElement<AdressTYPE>(_Adress_QNAME, AdressTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FastighetLanKod")
    public JAXBElement<String> createFastighetLanKod(String value) {
        return new JAXBElement<String>(_FastighetLanKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "ResultatfilSkapad")
    public JAXBElement<XMLGregorianCalendar> createResultatfilSkapad(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ResultatfilSkapad_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Land")
    public JAXBElement<String> createLand(String value) {
        return new JAXBElement<String>(_Land_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "DatumTom")
    public JAXBElement<XMLGregorianCalendar> createDatumTom(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumTom_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FodelselanKod")
    public JAXBElement<String> createFodelselanKod(String value) {
        return new JAXBElement<String>(_FodelselanKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "KundNrSlutkund")
    public JAXBElement<Integer> createKundNrSlutkund(Integer value) {
        return new JAXBElement<Integer>(_KundNrSlutkund_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlutAnvandarSekretessRattTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SlutAnvandarSekretessRatt")
    public JAXBElement<SlutAnvandarSekretessRattTYPE> createSlutAnvandarSekretessRatt(SlutAnvandarSekretessRattTYPE value) {
        return new JAXBElement<SlutAnvandarSekretessRattTYPE>(_SlutAnvandarSekretessRatt_QNAME, SlutAnvandarSekretessRattTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "AndringsDatum")
    public JAXBElement<XMLGregorianCalendar> createAndringsDatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AndringsDatum_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FolkbokfordKommunKod")
    public JAXBElement<String> createFolkbokfordKommunKod(String value) {
        return new JAXBElement<String>(_FolkbokfordKommunKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "HanvisningsPersonNr")
    public JAXBElement<String> createHanvisningsPersonNr(String value) {
        return new JAXBElement<String>(_HanvisningsPersonNr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "TidsstampelAvisering")
    public JAXBElement<XMLGregorianCalendar> createTidsstampelAvisering(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TidsstampelAvisering_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "OrgNr")
    public JAXBElement<String> createOrgNr(String value) {
        return new JAXBElement<String>(_OrgNr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FolkbokforingsfilInformationTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Folkbokforingsfil", scope = AviseringsunderlagTYPE.class)
    public JAXBElement<FolkbokforingsfilInformationTYPE> createAviseringsunderlagTYPEFolkbokforingsfil(FolkbokforingsfilInformationTYPE value) {
        return new JAXBElement<FolkbokforingsfilInformationTYPE>(_AviseringsunderlagTYPEFolkbokforingsfil_QNAME, FolkbokforingsfilInformationTYPE.class, AviseringsunderlagTYPE.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KundinfilInformationTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Kundinfil", scope = AviseringsunderlagTYPE.class)
    public JAXBElement<KundinfilInformationTYPE> createAviseringsunderlagTYPEKundinfil(KundinfilInformationTYPE value) {
        return new JAXBElement<KundinfilInformationTYPE>(_AviseringsunderlagTYPEKundinfil_QNAME, KundinfilInformationTYPE.class, AviseringsunderlagTYPE.class, value);
    }

}
