//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:19:45 em CET 
//


package se.sparavisering;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SlutAnvandarBehorighetTYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SlutAnvandarBehorighetTYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="KAT1"/>
 *     &lt;enumeration value="KAT2"/>
 *     &lt;enumeration value="KAT3"/>
 *     &lt;enumeration value="KAT4"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SlutAnvandarBehorighetTYPE")
@XmlEnum
public enum SlutAnvandarBehorighetTYPE {


    /**
     * Behörighetskategori 1
     * 
     */
    @XmlEnumValue("KAT1")
    KAT_1("KAT1"),

    /**
     * Behörighetskategori 2
     * 
     */
    @XmlEnumValue("KAT2")
    KAT_2("KAT2"),

    /**
     * Behörighetskategori 3
     * 
     */
    @XmlEnumValue("KAT3")
    KAT_3("KAT3"),

    /**
     * Behörighetskategori 4
     * 
     */
    @XmlEnumValue("KAT4")
    KAT_4("KAT4");
    private final String value;

    SlutAnvandarBehorighetTYPE(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SlutAnvandarBehorighetTYPE fromValue(String v) {
        for (SlutAnvandarBehorighetTYPE c: SlutAnvandarBehorighetTYPE.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
