//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:19:45 em CET 
//


package se.sparavisering;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}IdentifieringsInformationFil" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}Aviseringsunderlag" minOccurs="0"/>
 *         &lt;element ref="{http://skatteverket.se/spar/komponent/1.0}AviseringsPoster"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identifieringsInformationFil",
    "aviseringsunderlag",
    "aviseringsPoster"
})
@XmlRootElement(name = "SPARAvisering", namespace = "http://skatteverket.se/spar/instans/1.0")
public class SPARAvisering {

    @XmlElement(name = "IdentifieringsInformationFil")
    protected IdentifieringsInformationFilTYPE identifieringsInformationFil;
    @XmlElement(name = "Aviseringsunderlag")
    protected AviseringsunderlagTYPE aviseringsunderlag;
    @XmlElement(name = "AviseringsPoster", required = true)
    protected AviseringsPosterTYPE aviseringsPoster;

    /**
     * Gets the value of the identifieringsInformationFil property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifieringsInformationFilTYPE }
     *     
     */
    public IdentifieringsInformationFilTYPE getIdentifieringsInformationFil() {
        return identifieringsInformationFil;
    }

    /**
     * Sets the value of the identifieringsInformationFil property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifieringsInformationFilTYPE }
     *     
     */
    public void setIdentifieringsInformationFil(IdentifieringsInformationFilTYPE value) {
        this.identifieringsInformationFil = value;
    }

    /**
     * Gets the value of the aviseringsunderlag property.
     * 
     * @return
     *     possible object is
     *     {@link AviseringsunderlagTYPE }
     *     
     */
    public AviseringsunderlagTYPE getAviseringsunderlag() {
        return aviseringsunderlag;
    }

    /**
     * Sets the value of the aviseringsunderlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link AviseringsunderlagTYPE }
     *     
     */
    public void setAviseringsunderlag(AviseringsunderlagTYPE value) {
        this.aviseringsunderlag = value;
    }

    /**
     * Gets the value of the aviseringsPoster property.
     * 
     * @return
     *     possible object is
     *     {@link AviseringsPosterTYPE }
     *     
     */
    public AviseringsPosterTYPE getAviseringsPoster() {
        return aviseringsPoster;
    }

    /**
     * Sets the value of the aviseringsPoster property.
     * 
     * @param value
     *     allowed object is
     *     {@link AviseringsPosterTYPE }
     *     
     */
    public void setAviseringsPoster(AviseringsPosterTYPE value) {
        this.aviseringsPoster = value;
    }

}
