//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.12 at 07:19:47 em CET 
//


package se.skatteverket.spar.komponent._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the se.skatteverket.spar.komponent._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HanvisningsPersonNrByttTill_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "HanvisningsPersonNrByttTill");
    private final static QName _FysiskPersonId_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FysiskPersonId");
    private final static QName _FodelsetidTill_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FodelsetidTill");
    private final static QName _Fodelseforsamling_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Fodelseforsamling");
    private final static QName _UppdragsId_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "UppdragsId");
    private final static QName _Tillskrift_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Tillskrift");
    private final static QName _FodelsetidFran_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FodelsetidFran");
    private final static QName _Relation_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Relation");
    private final static QName _Tilltalsnamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Tilltalsnamn");
    private final static QName _KundNrLeveransMottagare_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "KundNrLeveransMottagare");
    private final static QName _ForMellanEfterNamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "ForMellanEfterNamn");
    private final static QName _SlutAnvandarId_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SlutAnvandarId");
    private final static QName _Sekretessmarkering_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Sekretessmarkering");
    private final static QName _DatumFrom_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "DatumFrom");
    private final static QName _Aviseringsnamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Aviseringsnamn");
    private final static QName _Efternamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Efternamn");
    private final static QName _SvenskMedborgare_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SvenskMedborgare");
    private final static QName _Mellannamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Mellannamn");
    private final static QName _KundNr_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "KundNr");
    private final static QName _Relationstyp_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Relationstyp");
    private final static QName _SlutAnvandarBehorighet_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SlutAnvandarBehorighet");
    private final static QName _Avregistreringsdatum_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Avregistreringsdatum");
    private final static QName _Tidsstampel_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Tidsstampel");
    private final static QName _SenasteAndringFolkbokforing_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SenasteAndringFolkbokforing");
    private final static QName _PersonId_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "PersonId");
    private final static QName _IdentifieringsInformation_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "IdentifieringsInformation");
    private final static QName _Kon_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Kon");
    private final static QName _AvregistreringsorsakKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "AvregistreringsorsakKod");
    private final static QName _IdentifieringsInformationFil_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "IdentifieringsInformationFil");
    private final static QName _DatumTom_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "DatumTom");
    private final static QName _FodelselanKod_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "FodelselanKod");
    private final static QName _Fodelsetid_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Fodelsetid");
    private final static QName _KundNrSlutkund_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "KundNrSlutkund");
    private final static QName _SlutAnvandarSekretessRatt_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SlutAnvandarSekretessRatt");
    private final static QName _Fornamn_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "Fornamn");
    private final static QName _SekretessAndringsdatum_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "SekretessAndringsdatum");
    private final static QName _HanvisningsPersonNr_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "HanvisningsPersonNr");
    private final static QName _OrgNrSlutkund_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "OrgNrSlutkund");
    private final static QName _OrgNr_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "OrgNr");
    private final static QName _HanvisningsPersonNrByttFran_QNAME = new QName("http://skatteverket.se/spar/komponent/1.0", "HanvisningsPersonNrByttFran");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: se.skatteverket.spar.komponent._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FilinformationTYPE }
     * 
     */
    public FilinformationTYPE createFilinformationTYPE() {
        return new FilinformationTYPE();
    }

    /**
     * Create an instance of {@link ForMellanEfterNamnTYPE }
     * 
     */
    public ForMellanEfterNamnTYPE createForMellanEfterNamnTYPE() {
        return new ForMellanEfterNamnTYPE();
    }

    /**
     * Create an instance of {@link RelationTYPE }
     * 
     */
    public RelationTYPE createRelationTYPE() {
        return new RelationTYPE();
    }

    /**
     * Create an instance of {@link IdentifieringsInformationFilTYPE }
     * 
     */
    public IdentifieringsInformationFilTYPE createIdentifieringsInformationFilTYPE() {
        return new IdentifieringsInformationFilTYPE();
    }

    /**
     * Create an instance of {@link MedieinformationTYPE }
     * 
     */
    public MedieinformationTYPE createMedieinformationTYPE() {
        return new MedieinformationTYPE();
    }

    /**
     * Create an instance of {@link PersonIdTYPE }
     * 
     */
    public PersonIdTYPE createPersonIdTYPE() {
        return new PersonIdTYPE();
    }

    /**
     * Create an instance of {@link IdentifieringsInformationTYPE }
     * 
     */
    public IdentifieringsInformationTYPE createIdentifieringsInformationTYPE() {
        return new IdentifieringsInformationTYPE();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "HanvisningsPersonNrByttTill")
    public JAXBElement<String> createHanvisningsPersonNrByttTill(String value) {
        return new JAXBElement<String>(_HanvisningsPersonNrByttTill_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FysiskPersonId")
    public JAXBElement<String> createFysiskPersonId(String value) {
        return new JAXBElement<String>(_FysiskPersonId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FodelsetidTill")
    public JAXBElement<XMLGregorianCalendar> createFodelsetidTill(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_FodelsetidTill_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Fodelseforsamling")
    public JAXBElement<String> createFodelseforsamling(String value) {
        return new JAXBElement<String>(_Fodelseforsamling_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "UppdragsId")
    public JAXBElement<Long> createUppdragsId(Long value) {
        return new JAXBElement<Long>(_UppdragsId_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Tillskrift")
    public JAXBElement<String> createTillskrift(String value) {
        return new JAXBElement<String>(_Tillskrift_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FodelsetidFran")
    public JAXBElement<XMLGregorianCalendar> createFodelsetidFran(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_FodelsetidFran_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Relation")
    public JAXBElement<RelationTYPE> createRelation(RelationTYPE value) {
        return new JAXBElement<RelationTYPE>(_Relation_QNAME, RelationTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Tilltalsnamn")
    public JAXBElement<Integer> createTilltalsnamn(Integer value) {
        return new JAXBElement<Integer>(_Tilltalsnamn_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "KundNrLeveransMottagare")
    public JAXBElement<Integer> createKundNrLeveransMottagare(Integer value) {
        return new JAXBElement<Integer>(_KundNrLeveransMottagare_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForMellanEfterNamnTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "ForMellanEfterNamn")
    public JAXBElement<ForMellanEfterNamnTYPE> createForMellanEfterNamn(ForMellanEfterNamnTYPE value) {
        return new JAXBElement<ForMellanEfterNamnTYPE>(_ForMellanEfterNamn_QNAME, ForMellanEfterNamnTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SlutAnvandarId")
    public JAXBElement<String> createSlutAnvandarId(String value) {
        return new JAXBElement<String>(_SlutAnvandarId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SekretessmarkeringTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Sekretessmarkering")
    public JAXBElement<SekretessmarkeringTYPE> createSekretessmarkering(SekretessmarkeringTYPE value) {
        return new JAXBElement<SekretessmarkeringTYPE>(_Sekretessmarkering_QNAME, SekretessmarkeringTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "DatumFrom")
    public JAXBElement<XMLGregorianCalendar> createDatumFrom(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumFrom_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Aviseringsnamn")
    public JAXBElement<String> createAviseringsnamn(String value) {
        return new JAXBElement<String>(_Aviseringsnamn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Efternamn")
    public JAXBElement<String> createEfternamn(String value) {
        return new JAXBElement<String>(_Efternamn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SvenskMedborgareTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SvenskMedborgare")
    public JAXBElement<SvenskMedborgareTYPE> createSvenskMedborgare(SvenskMedborgareTYPE value) {
        return new JAXBElement<SvenskMedborgareTYPE>(_SvenskMedborgare_QNAME, SvenskMedborgareTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Mellannamn")
    public JAXBElement<String> createMellannamn(String value) {
        return new JAXBElement<String>(_Mellannamn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "KundNr")
    public JAXBElement<Integer> createKundNr(Integer value) {
        return new JAXBElement<Integer>(_KundNr_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationstypTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Relationstyp")
    public JAXBElement<RelationstypTYPE> createRelationstyp(RelationstypTYPE value) {
        return new JAXBElement<RelationstypTYPE>(_Relationstyp_QNAME, RelationstypTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlutAnvandarBehorighetTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SlutAnvandarBehorighet")
    public JAXBElement<SlutAnvandarBehorighetTYPE> createSlutAnvandarBehorighet(SlutAnvandarBehorighetTYPE value) {
        return new JAXBElement<SlutAnvandarBehorighetTYPE>(_SlutAnvandarBehorighet_QNAME, SlutAnvandarBehorighetTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Avregistreringsdatum")
    public JAXBElement<String> createAvregistreringsdatum(String value) {
        return new JAXBElement<String>(_Avregistreringsdatum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Tidsstampel")
    public JAXBElement<XMLGregorianCalendar> createTidsstampel(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Tidsstampel_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SenasteAndringFolkbokforing")
    public JAXBElement<XMLGregorianCalendar> createSenasteAndringFolkbokforing(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SenasteAndringFolkbokforing_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonIdTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "PersonId")
    public JAXBElement<PersonIdTYPE> createPersonId(PersonIdTYPE value) {
        return new JAXBElement<PersonIdTYPE>(_PersonId_QNAME, PersonIdTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifieringsInformationTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "IdentifieringsInformation")
    public JAXBElement<IdentifieringsInformationTYPE> createIdentifieringsInformation(IdentifieringsInformationTYPE value) {
        return new JAXBElement<IdentifieringsInformationTYPE>(_IdentifieringsInformation_QNAME, IdentifieringsInformationTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KonTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Kon")
    public JAXBElement<KonTYPE> createKon(KonTYPE value) {
        return new JAXBElement<KonTYPE>(_Kon_QNAME, KonTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AvregistreringsorsakKodTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "AvregistreringsorsakKod")
    public JAXBElement<AvregistreringsorsakKodTYPE> createAvregistreringsorsakKod(AvregistreringsorsakKodTYPE value) {
        return new JAXBElement<AvregistreringsorsakKodTYPE>(_AvregistreringsorsakKod_QNAME, AvregistreringsorsakKodTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifieringsInformationFilTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "IdentifieringsInformationFil")
    public JAXBElement<IdentifieringsInformationFilTYPE> createIdentifieringsInformationFil(IdentifieringsInformationFilTYPE value) {
        return new JAXBElement<IdentifieringsInformationFilTYPE>(_IdentifieringsInformationFil_QNAME, IdentifieringsInformationFilTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "DatumTom")
    public JAXBElement<XMLGregorianCalendar> createDatumTom(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DatumTom_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "FodelselanKod")
    public JAXBElement<String> createFodelselanKod(String value) {
        return new JAXBElement<String>(_FodelselanKod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Fodelsetid")
    public JAXBElement<XMLGregorianCalendar> createFodelsetid(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Fodelsetid_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "KundNrSlutkund")
    public JAXBElement<Integer> createKundNrSlutkund(Integer value) {
        return new JAXBElement<Integer>(_KundNrSlutkund_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SlutAnvandarSekretessRattTYPE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SlutAnvandarSekretessRatt")
    public JAXBElement<SlutAnvandarSekretessRattTYPE> createSlutAnvandarSekretessRatt(SlutAnvandarSekretessRattTYPE value) {
        return new JAXBElement<SlutAnvandarSekretessRattTYPE>(_SlutAnvandarSekretessRatt_QNAME, SlutAnvandarSekretessRattTYPE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "Fornamn")
    public JAXBElement<String> createFornamn(String value) {
        return new JAXBElement<String>(_Fornamn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "SekretessAndringsdatum")
    public JAXBElement<XMLGregorianCalendar> createSekretessAndringsdatum(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SekretessAndringsdatum_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "HanvisningsPersonNr")
    public JAXBElement<String> createHanvisningsPersonNr(String value) {
        return new JAXBElement<String>(_HanvisningsPersonNr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "OrgNrSlutkund")
    public JAXBElement<String> createOrgNrSlutkund(String value) {
        return new JAXBElement<String>(_OrgNrSlutkund_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "OrgNr")
    public JAXBElement<String> createOrgNr(String value) {
        return new JAXBElement<String>(_OrgNr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://skatteverket.se/spar/komponent/1.0", name = "HanvisningsPersonNrByttFran")
    public JAXBElement<String> createHanvisningsPersonNrByttFran(String value) {
        return new JAXBElement<String>(_HanvisningsPersonNrByttFran_QNAME, String.class, null, value);
    }

}
