//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.11 at 09:36:20 PM CET 
//


package se.skatteverket.spar.komponent._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelationstypTYPE.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RelationstypTYPE">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="V"/>
 *     &lt;enumeration value="M"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RelationstypTYPE")
@XmlEnum
public enum RelationstypTYPE {


    /**
     * Vårdnadshavare
     * 
     */
    V,

    /**
     * Maka/Make/Partner
     * 
     */
    M;

    public String value() {
        return name();
    }

    public static RelationstypTYPE fromValue(String v) {
        return valueOf(v);
    }

}
